### ISSUE TITLE
Include in the F-Droid repository

### ISSUE THREAD

**Issue by UnderSampled** [DreierF/MyTargets#106]
F-Droid is the premiere source for FOSS Android apps. Some modifications are required to ensure no proprietary libraries are used (i.e. Google play services). If the features these libaries provide are still desirable to some users, alternatives could be found or a simple build flag could be set up.

**Comment by DreierF** [comment]
Honestly I don't have great interest in creating a stripped down version of the app. At the moment I'm using the Google Play Services for the wearable app and Google Nearby and Cast will follow at some point. For both no real alternatives exist afaik and having to test two versions of the app and deploying them will also produce an overhead of work.
