### ISSUE TITLE
Enhance statistics to provide more useful insights in the users training status

### ISSUE THREAD

**Issue by DreierF** [DreierF/MyTargets#11]
- [x] It should be possible to see statistics for all trainings, single or a set of trainings as well as individual rounds.
- [x] Add filtering option to only take specific targets, distances, arrows, bows into account.
- [x] Add arrow ranking, which shows the best arrows and a dispersion pattern for each arrow. The value could be average rings hit. Maybe have a setting to choose whether best are chosen by average achieved points or by grouping (see #35)

For the implementation of the diagrams:
https://github.com/PhilJay/MPAndroidChart

**Comment by Tirpitz93** [comment]
Add graph by cluster analysis to graph view

**Comment by DreierF** [comment]
Redesign graph like this
![components_cards_action5](https://cloud.githubusercontent.com/assets/5631865/16757826/7f680ab6-480e-11e6-86d8-6d9311362bf3.png)

**Comment by Tirpitz93** [comment]
Maybe have dropdown to select ranking value (% achieved points, grouping etc)

**Comment by DreierF** [comment]
Add filtering option to only take specific distances, arrows, bows into account.
