### ISSUE TITLE
Automated backup to cloud

### ISSUE THREAD

**Issue by DreierF** [DreierF/MyTargets#14]
Add an option to the app settings that allows the user to automatically sync its data to a cloud drive like Google Drive, Dropbox or similar.

**Comment by fregor77** [comment]
Have you looked at this: https://developer.android.com/guide/topics/data/backup.html

**Comment by DreierF** [comment]
This is already supported. But I can understand that it is better to have some control over the backups ;-)

**Comment by DreierF** [comment]
https://medium.com/glucosio-project/build-a-nice-ux-to-backup-and-sync-your-app-data-on-google-drive-3-3-a3b598cab68b?_utm_source=1-2-2#.qy7dz6haq
