### ISSUE TITLE
Black background in pie chart

### ISSUE THREAD

**Issue by giosh94mhz** [DreierF/MyTargets#151]
[Following the thread on G+]

In "whole app stats" the pie chart has black background. 

![screenshot_20160916-142030](https://cloud.githubusercontent.com/assets/5219975/18825027/8fcd8888-83c6-11e6-9819-f85da51fa99b.png)

This seems to happens always, but if look closely you'll see that I hit some few 3 (don't laugh :). By clicking on that 3, the view change to this "black halo":

![screenshot_20160918-220020](https://cloud.githubusercontent.com/assets/5219975/18825038/a032d0c0-83c6-11e6-9817-99e415896e47.png)

So it definitely seems data driven. A simple solution would be to collapse all trailing results into a single slice; in my case would be a "<= 4" slice.

**Comment by DreierF** [comment]
Thanks for tring this out. I was able to reproduce the issue by inserting 90 ends. Hope I will find a fix soon

**Comment by DreierF** [comment]
This issue is caused by https://github.com/PhilJay/MPAndroidChart/issues/2329

**Comment by giosh94mhz** [comment]
Nice catch! Maybe you could work your way around, by squashing all the lower result into one. If it doesn't take more than 10min of course, is not a priority.

**Comment by ribuluo000** [comment]
@giosh94mhz @DreierF 
I found a fix, and you can try it.
https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/main/java/com/github/mikephil/charting/utils/Utils.java
in this file,change public final static float FLOAT_EPSILON = Float.intBitsToFloat(Float.floatToIntBits(1f) + 1); 
to public final static float FLOAT_EPSILON = Float.intBitsToFloat(0);//todo new resolve the piechart not show the part less than 1.

and all the part will be draw in the right way.
Good luck!

![image](https://cloud.githubusercontent.com/assets/9551756/19210104/b90a35f0-8d4b-11e6-9047-3130b619672d.png)

**Comment by giosh94mhz** [comment]
Well done @ribuluo000. Looks like the good old floating point issues :)
