### ISSUE TITLE
Hits + misses > total arrows shot

### ISSUE THREAD

**Issue by smartavionics** [DreierF/MyTargets#155]
Hi,

Just noticed that in a Portsmouth round (20 x 3 arrows) I shot yesterday, the scorecard says hits = 60 and misses = 1. Which totals 61 arrows! It should say hits = 59.

Also, while I'm here, the one feature I really miss in your otherwise very nice app is a running total score so you can see how you are doing as the ends progress.

Cheers
[Portsmouth 5-10-16.pdf](https://github.com/DreierF/MyTargets/files/513071/Portsmouth.5-10-16.pdf)

**Comment by DreierF** [comment]
Please try the latest beta version. The issue should be fixed there.

**Comment by DreierF** [comment]
https://plus.google.com/communities/102686119334423317437

**Comment by DreierF** [comment]
Is the issue gone?

**Comment by smartavionics** [comment]
Sorry, haven't been able to try the beta app yet as my app has no updates showing.

**Comment by DreierF** [comment]
Did you follow the instructions?
How to get the latest Beta Version:
1. Join this community
2. Visit the following Url and click on become beta tester: https://play.google.com/apps/testing/de.dreier.mytargets

**Comment by smartavionics** [comment]
Yes, I did that but maybe I screwed up, will try again...

**Comment by smartavionics** [comment]
Yes, it says I am already a tester and it can take a few hours for the app to arrive (patience required)

Any thoughts on my comment about having a running total displayed while you are shooting?

**Comment by DreierF** [comment]
Is part of the new beta as well ;-) #32

**Comment by smartavionics** [comment]
OK, I got the new beta and, yes, the number of hits is now correct.

One comment: on my phone I have to scroll the screen left to see the number of hits and the average. I would prefer if those were shown below when the screen isn't wide enough to display all the info on one line.

**Comment by DreierF** [comment]
I created a new issue (#162) for that and will close this one now, since the original issue is resolved ;-)
