### ISSUE TITLE
Date of training

### ISSUE THREAD

**Issue by maksimdomasev** [DreierF/MyTargets#179]
Noticed that when I specify the day of the training when recording the scores the app saves me the day prior to the one I specify, thus, if I want to display days correctly I need to record the scores under the following day of the actual date

**Comment by DreierF** [comment]
Where do the dates get shown wrong? I was able to reproduce it for the csv file, but not on the UI.

**Comment by maksimdomasev** [comment]
It is when I in the training part begin recording new score sheet. I name the title, the date comes after it (displayed right), but the saved list of scores is displayed under the previous day. The same occurs if I edit score list — the date jumps one day back after it is saved.

**Comment by maksimdomasev** [comment]
Managed to obtain some more information about this issue. It appeared on two phones running android 4.X on MTK processors. On ASUS phone running android 5.X on Intel processor this bug did not appear, also it did not appear on other phone (cannot tell exactly android version) owned by my archery collegue.

**Comment by DreierF** [comment]
Should be fixed when #199 gets merged to develop
