### ISSUE TITLE
Add intelligent finger slip detection for shot plotting

### ISSUE THREAD

**Issue by DreierF** [DreierF/MyTargets#218]

**Comment by Tirpitz93** [comment]
this sounds really interesting, how is this going to work?
is it just so you can mark an arrow as "discard" and not use it in consistency stats etc?

**Comment by DreierF** [comment]
My assumption is that the arrow position is relatively precise until a short moment before releasing the finger. During the release the shot position often (at least from my experience) moves some direction. So the idea was to use the position briefly before the release event.
Either by using going back by static time interval from the release or by applying some more advanced logic.
But I haven't thought too much about the implementation details yet.

**Comment by DreierF** [comment]
It's meant for the phone app

**Comment by DreierF** [comment]
Closed with fe9a403b9f42082a021da84d7bb4721375f5973e
