### ISSUE TITLE
Cannot add next round

### ISSUE THREAD

**Issue by GizmoSK** [DreierF/MyTargets#239]
After last beta update (2.4.0-Beta5(61)) it is not possible to add round 2nd, 3rd etc only 1st round. I tried for new and older trainings. Nothing works. Did you change something? 
For example: create new training with standard round, choose WA 18(40cm). Enter some score in round 1. Then exit and try add round 2. It is not possible because the orange button does not appear in the right bottom of the page....

**Comment by DreierF** [comment]
That is intended for standard rounds, but should work for free training. How did you create the training?

**Comment by GizmoSK** [comment]
As I described in first post:
1. orange button on the main screen choose - training with standard round
2. choose wa 18 (40cm) 18m:20*3arrows (40cm target)
3. choose bow/arrows and other options
4. thick "ok" ()
5. now you should be in adding score. Add some if you want to but it is not necessary
6. go back two times you should be on main page for training
7. there is no orange button to add next round!
When you go one more time back to the main page the orange button is there but it adds whole new training but I want only next round

**Comment by DreierF** [comment]
I'm sorry. I must have overseen the create training with standard round.
That's (right now) the intended behavior. Because WA 18 is defined to have exactly one round with 20 ends. That's why the button is missing.
