### ISSUE TITLE
add a way to add note/worklog

### ISSUE THREAD

**Issue by valgit** [DreierF/MyTargets#256]
It would be interesting to be able to add notes or worklog and associate it to a training/round etc.. to have some history

**Comment by DreierF** [comment]
Sounds interesting.
Could you be a little bit more specific how you image this to work, some use case and in how far it differs from the training and round comments already implemented (or how it complements them)?

**Comment by valgit** [comment]
@DreierF the idea would be to be able to add note during or after a training/round, from what I understand the comments for now is only at creation.
For eg, after a round, you could add your feeling about how your session has been, or what you change/do during the round etc.

**Comment by DreierF** [comment]
You can also change the comments currently after the training. But they should probably be a little bit easier accessible.

**Comment by valgit** [comment]
@DreierF I've yet to find how I can change the comment on 2.4.1 (my current version), maybe we need to put in more accessible ?

**Comment by DreierF** [comment]
Long press the round or training you want to comment on, select the ✏️ symbol in the toolbar, add a comment and save ;-)

**Comment by DreierF** [comment]
Closed with 0807312
