### ISSUE TITLE
Allow user to enter scores without specifying arrow numbers

### ISSUE THREAD

**Issue by fish-face** [DreierF/MyTargets#277]
Such close attention is not required for all archers, and it makes it take longer to enter scores. All that should be needed would be a checkbox along with the others when adding scores to turn off arrow identification. It would be particularly useful in conjunction the existing mode entering arrows solely by number, to make scoring a round for a competition as quick as possible.

For reference I am used to Archery Companion which is (old and unmaintained, and)  geared towards scoring rounds using an interface that looks like an ordinary score sheet. If you're interested in making some changes that would make that possible I can make some another feature request.

**Comment by DreierF** [comment]
The option is already there. When you create a new training, untick the option "arrow numbering". But I agree that the op Putin should be moved alongside the other options in the input screen and is already disabled by default in the latest beta.

**Comment by fish-face** [comment]
Ah, I must have missed that and never tried to create a new Training while testing. Cheers!
