### ISSUE TITLE
Increase arrow limit to 24

### ISSUE THREAD

**Issue by DreierF** [DreierF/MyTargets#280]
In elimination rounds it can go up to 24 arrows.
Arrow numbers in turn should also be increased.

**Comment by madmaxmarchhare** [comment]
Actually, increasing to only 24 still wouldn't be sufficient for the way I number my arrows. Can you just allow for a select-able upper limit to the number?

**Comment by DreierF** [comment]
24 is meant here as the upper limit of how many arrows you can enter per end. Arrow numbers may of course be bigger than that and yes I'll make them adjustable.

**Comment by DreierF** [comment]
Closed with a5132135088da481bf5affba91efb01dfeb4091f
