### ISSUE TITLE
Export trainings and configuration to an API

### ISSUE THREAD

**Issue by Jojolam44** [DreierF/MyTargets#283]
Hi,

Is there any way to export my training to an external server via an API ?

Our trainer use a Google Drive sheet to follow our trainings but manually copying results from your amazing application to this Google Drive is boring. 
I want to create a web application to mutualise his differents sheets and generate an API access to easily import datas.

That's why I ask you this feature :-)
It don't have to be very secure, it can just be a POST XML with a token in URL.

Thanks for your answer and have a nice day !

Jonathan

**Comment by DreierF** [comment]
At the moment there are basically two ways to get data out of the app.
Create a backup and read the sqlite db, which is packed inside the backup's zip file, or export the training data as csv.
Even though I can understand that you want to have this integrated in the app, I don't see this a feature for the core app.
I would suggest to create a separate android app which accepts csv files and uploads them to your server. You can then export your training data and select your new app from the share menu.

What do you think?

**Comment by valgit** [comment]
@Jojolam44 can you explain a bit more what your coach is doing with the sheet ? what sort of result he needs ? is it the full CSV with all arrows information ?

**Comment by Jojolam44** [comment]
He's doing stats with arrows results and frequency of trainings.
He also add informations about bow and arrows but that's much more for the archer than the coatch :-)

I'll have a look to the share functionnality with CSV file. I think that's a good alternative !

Thanks for your answer.
