### ISSUE TITLE
Diagram building issue

### ISSUE THREAD

**Issue by True-to-life** [DreierF/MyTargets#285]
When you start inputing your practice data at the end of the day and finish it next day, diagram of this training is built with an error. 

reproduce: Start inputing practice result at the end of the day. Make last input after next day starts. Open practice statistics
result: Diagram shows us whole day, some result are at its beginning, some are at the end, and one all-day long line between them
Expected Result: diagram shows us only praticing period despite the change of the date # @
![mytargets](https://user-images.githubusercontent.com/30315212/28412850-19ce6054-6d4e-11e7-848c-0a4e95ad022c.png)

**Comment by DreierF** [comment]
I assumed this case would never happen. Looks like I was wrong 😅
