### ISSUE TITLE
Allow more arrows than 1-12

### ISSUE THREAD

**Issue by brucemarnold** [DreierF/MyTargets#286]
I often have more than 36 arrows numbered at any one time, and it's really limiting to only be able to choose between numbers 1-12 when recording which arrow I shot. I don't want to have to break the group up into 3 groups of 12 for a lot of different reasons.

**Comment by DreierF** [comment]
related to #280

**Comment by DreierF** [comment]
Closed with 73ab6440fcf74fe52e02815fbd33dd9c573efe6c
