### ISSUE TITLE
Tell me the average score for each arrow over time/use

### ISSUE THREAD

**Issue by brucemarnold** [DreierF/MyTargets#287]
I thought MyTargets used to display the average points/score for each arrow (as numbered) used? Now it displays... ?? some sort of fractional deviation? Maybe make this selectable?

**Comment by DreierF** [comment]
Yeah, I'll change that back. At the moment it shot shows the group size.

**Comment by DreierF** [comment]
Closed in ddf75aedbc03c9abd9d6b96e5860a0b86a7ea25f
