### ISSUE TITLE
Pin screen if in Passe modus

### ISSUE THREAD

**Issue by reox** [DreierF/MyTargets#290]
I know it is possible to pin the screen to be rendered over the lockscreen, but other apps like Google Navigation or Kodi can do this automatically.
It would be very convenient to have such a feature configurable, so when you are shooting a round and you lock the screen, you will stay in it.

**Comment by DreierF** [comment]
I'm not really sure what you mean. I know that you can set a different background image, a sticky notification and up to Marshmallow or so lock screen widgets.
Do you maybe have a screenshot?
What would you expect to see/be able to do there?

**Comment by reox** [comment]
For example: The Kodi App Kore: https://f-droid.org/packages/org.xbmc.kore/ has a setting to show the activity of the remote control, even if the phone is locked.
In the code it looks like this: https://github.com/xbmc/Kore/blob/cb430aa20d13c56a04a800275bd92161ce41cbf8/app/src/main/java/org/xbmc/kore/ui/sections/remote/RemoteActivity.java#L174 / https://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#FLAG_SHOW_WHEN_LOCKED
Which means, if you use the Kore app and lock your device, the first thing you see on unlocking is the remote control and not your lockscreen.

**Comment by DreierF** [comment]
Thanks for the link to the Docs :+1:

**Comment by DreierF** [comment]
Use the same technique for the timer as well.

**Comment by DreierF** [comment]
Closed via c265b20
