### ISSUE TITLE
describe sqlite table usage

### ISSUE THREAD

**Issue by valgit** [DreierF/MyTargets#300]
Can you give information on how you use the different table in order to contribute.
can you give more information for developer who want to contribute ?

**Comment by DreierF** [comment]
As a first starting point I have added a ER-diagram to the [wiki page](https://github.com/DreierF/MyTargets/wiki).
Besides getting an overview is there anything that would need more explanation?

**Comment by valgit** [comment]
good news @DreierF , it will help a lot.thanks
