### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by valgit** [DreierF/MyTargets#304]
when compiling I got : "Error:Could not get unknown property 'CROWDIN_API_KEY' for task ':crowdinUpload' of type com.mendhak.gradlecrowdin.UploadSourceFileTask."

**Comment by DreierF** [comment]
CROWDIN_API_KEY is a private access key to sync the translations with Crowdin. Comment one of the last lines in the top level build.gradle file with script-crowdin.gradle and the error should disappeared

**Comment by valgit** [comment]
@DreierF can you elaborate more ? did we need to register to have our own private key ?

note: I also have this one : "Gradle sync failed: Could not get unknown property 'KEYSTORE_PASSWORD' for SigningConfig_Decorated{name=release, storeFile=<path>\MyTargets\keystore.jks, storePassword=null, keyAlias=null, keyPassword=null, storeType=<path>\MyTargets\keystore.jks, v1SigningEnabled=true, v2SigningEnabled=true} of type com.android.build.gradle.internal.dsl.SigningConfig.
			Consult IDE log for more details (Help | Show Log)"

**Comment by DreierF** [comment]
No you don't have to register. The key provides full access to the translations and therefore I can't share it, but Travis does the syncing as well. So just comment the script and don't commit it :wink:
Regarding the KEYSTORE_PASSWORD and KEY_PASSWORD. You can replace the keystone.jks by your own keystore if you want to test the release configuration or just set them to an arbitrary value in the gradle.properties file.

**Comment by valgit** [comment]
now I have : 
Error:Execution failed for task ':app:processRegularDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 

what should i do ?
note: there is a real need of "howto setup a compilation env for MyTargets"

**Comment by DreierF** [comment]
Totally agree with you here, but until now there was no need to, since no one was interested in contributing 😉 (And I'm really sorry for the issues)
Try commenting `apply plugin: 'com.google.gms.google-services'` at the bottom of the app's build.gradle

**Comment by DreierF** [comment]
I just pushed a new commit to develop (3bbd83f62af8baebfc228fa55698ab8a5e03b417), which should make the setup work without any adjustments on your side.
Please try it and tell me if it works for you!

**Comment by valgit** [comment]
thanks @DreierF , I've successufully compile without any further modification !
