### ISSUE TITLE
export dispersion pattern bug

### ISSUE THREAD

**Issue by valgit** [DreierF/MyTargets#332]
when you export the dispersion pattern there is two bugs :  
* the time/date of file is wrong (01/0/11970 ;-)
* the pattern is not exported only the ends

**Comment by DreierF** [comment]
The time/date is only a random number ATM to avoid file conflicts, but should of course include the date/time.
I don't quite get your second point. What do you mean by that?

**Comment by valgit** [comment]
for the date time : 
there is no date/time in exif nor at the creation wher ethe OS state that the file as been created at 01/01/1970 !!!

![timedate](https://user-images.githubusercontent.com/4363000/34726772-3fd35b30-f555-11e7-96b4-923e69076256.jpg)

for the case of pattern here some sample : 
* result from export : 
![dispersion_pattern211979319](https://user-images.githubusercontent.com/4363000/34726684-10d8faec-f555-11e7-8bec-19cd8a45f2bd.jpg)

* result from screenshot : 
![screenshot_20180109-154119](https://user-images.githubusercontent.com/4363000/34726692-161a102c-f555-11e7-9882-2b5ce389ffd7.png)

**Comment by DreierF** [comment]
Now I got it. You meant the aggregation visualization.

**Comment by DreierF** [comment]
Is there any use case for you, for which you need the exif data?

**Comment by valgit** [comment]
@DreierF no real use case, only a problem when I upload to a server, where it set creation date from Exif, so they have a bad date

**Comment by DreierF** [comment]
The app did not attach any exif data, so the application you used to upload the image set it to 0, which corresponds to the 1.1.1970. Anyway the app now attaches the current timestamp as exif date to the image dispersion pattern and scoreboard
