### ISSUE TITLE
Edit date of rounds within free training. 

### ISSUE THREAD

**Issue by cel106** [DreierF/MyTargets#343]
Mytargets is a great archery app, really enjoyable to use. Thank you Florian!

To use Free training, I've just been adding rounds each night; it's really nice to keep all the free training rounds under one entry on the first screen. 
I understand now that I've been doing it wrong, because months of training are collected under a single date.
If I could find the database, I don't mind taking a copy and trying to split the training myself, but I can't  find where it is stored by mytargets.
I'm sorry if this isn't the right place for a support request.

**Comment by DreierF** [comment]
The database is stored in an app private area, which you can only access with root access. But you can get access to the database by taking a backup of the app (Settings->Backup), which will create a zip file on your phones SD card. It will contain a db file (SQLite). When you have finished the manipulations zip it again and import it into the app again 😉

**Comment by cel106** [comment]
Dear Florian,

That's perfect! Thank you.

Do you need me to close the github issue?

May all your arrows find the gold.

Thanks again,

Col.


On 27 Jan 2018 07:32, "Florian Dreier" <notifications@github.com> wrote:

The database is stored in an app private area, which you can only access
with root access. But you can get access to the database by taking a backup
of the app (Settings->Backup), which will create a zip file on your phones
SD card. It will contain a db file (SQLite). When you have finished the
manipulations zip it again and import it into the app again 😉

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/DreierF/MyTargets/issues/343#issuecomment-360966978>,
or mute the thread

**Comment by cel106** [comment]
Dear Florian,

The latest update to mytargets is great!

I'm really liking the score entry staying in front of the lock screen, and
setting the dispersion overlay from within the statistics view.

Thanks for your continuing efforts!

Col.
