### ISSUE TITLE
Just using shooting board

### ISSUE THREAD

**Issue by smkazemi** [DreierF/MyTargets#345]
Hi, I need to create a shooting board like this App and I do not need to use all the code.
What classes should I use?
Or would I better ask how to create a shooting board?
Thanks so much brother .

**Comment by DreierF** [comment]
Hi, I guess you mean the scoreboard?
Just search for Scoreboard to find the related classes. They are all placed in one package.
Out of curiosity: What are you planning to do🙂?

**Comment by smkazemi** [comment]
Yes thank you
In fact, I'm creating a similar Android application for a company, but not completely, and I have to use a ScoreBoard for it.

**Comment by DreierF** [comment]
Ok, you are aware of the licence of MyTargets? It's under GPL 2, which means you have to open source your app if you reuse parts of this app.

**Comment by smkazemi** [comment]
Ok , I understood ... tnx bro
I can't open source this app , so you can guide me to solve my problem ? !
my problem is to rate each region
I need an idea or solution .

**Comment by DreierF** [comment]
I'm sorry, but I can't help you with that.
