### ISSUE TITLE
Photo after scores has been entered

### ISSUE THREAD

**Issue by reox** [DreierF/MyTargets#361]
Yesterday I tried to add a photo after I already entered the shots. The photo was shown in the lower right corner and I pressed the back button to get to the end view.
But the icon was again the camera and not the image. Also in the end listing, the images are not shown.
Today I found out that the image is only saved if it is shot before entering any shots:

1) create new training
2) create new end
3) now create the photo
![screenshot_20180421-105118](https://user-images.githubusercontent.com/431045/39082369-9f3df4c2-4541-11e8-9650-a6085d018ec0.png)

4) Icon will switch to gallery icon
![screenshot_20180421-105123](https://user-images.githubusercontent.com/431045/39082370-a54e3642-4541-11e8-9ac0-35d443fb17c1.png)

5) enter shots
6) next end
7) now enter shots
8) click on take photo
![screenshot_20180421-105223](https://user-images.githubusercontent.com/431045/39082371-a930d436-4541-11e8-92f9-a1911f147fd0.png)

9) photo seems to be taken correctly but the icon has not changed
![screenshot_20180421-105228](https://user-images.githubusercontent.com/431045/39082374-addb9660-4541-11e8-9079-1bef51b3a60b.png)

10) in the end list, only the first end has the image attached

![screenshot_20180421-105247](https://user-images.githubusercontent.com/431045/39082375-b01a656e-4541-11e8-85b2-783ba882ef8f.png)

I think the intention was to have the photo feature, so you can quickly capture the score and enter it later, but I also use it to take pictures of nice shots. So I do not want to remember all the time to take the picture first :smile: 

Android 7.1.2 / LineageOS 14.1
Nexus 5
MyTargets 3.0.3 (85)

**Comment by DreierF** [comment]
Thanks for the detailed bug report!
