### ISSUE TITLE
5 zone scoring

### ISSUE THREAD

**Issue by rikroto** [DreierF/MyTargets#364]
Hi, just started using the app and love it. But our indoor competition (new zealand) often uses 5 zone scoring, where 10&9 is scored ad 9, 8&7 scored as 7, etc, so only scores are 9,7,5,3,1.  Your app with its graphical shot scoring only seems to allow 10 zobe scoring. Can 5 zone scoring be added?
Regards
Richard

**Comment by DreierF** [comment]
Hey there,
Thanks! This should already be possible if you change the scoring style for the 10 zone target accordingly to "9,7,5,3,1". That's the drop-down at the top when you select the target face.

**Comment by rikroto** [comment]
Thanks, i didn't notice that. Excellant product.
