### ISSUE TITLE
Clean checkout will not compile

### ISSUE THREAD

**Issue by mrj9600** [DreierF/MyTargets#391]
I have made a clean checkout and executes gradlew.bat from root directory. This gives the following errors:
Configure project :app
GMS secret is missing!

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Check your service account configuration. Json credentials cannot specify a Service Account email while PKCS12 credentials must do so.

**Comment by mrj9600** [comment]
I have managed to build the project by removing varioud google play and signing sections from build.gradle file (locally).
I guess my issue is that I dont have a developer key as I have never deployed any app to google play store.

**Comment by averyvigolo** [comment]
For those who hit the same issue, the problematic plugins are `com.github.triplet.play` and `io.fabric`. I applied the following changes and can build with `gradle assembleRelease -x test`. If you want tests you may want to add `android { lintOptions { abortOnError false } }` so linting errors don't fail the build.

```diff
diff --git a/app/build.gradle b/app/build.gradle
index 4b9d3b78..24b46dcd 100644
--- a/app/build.gradle
+++ b/app/build.gradle
@@ -14,14 +14,14 @@
  */
 plugins {
     id 'com.android.application'
-    id 'com.github.triplet.play' version '2.2.0'
+    // id 'com.github.triplet.play' version '2.2.0'
     id 'com.getkeepsafe.dexcount'
 }

 apply plugin: 'kotlin-android'
 apply plugin: 'kotlin-kapt'
 apply plugin: 'kotlin-android-extensions'
-apply plugin: 'io.fabric'
+// apply plugin: 'io.fabric'
 apply plugin: 'androidx.navigation.safeargs'

 android {
@@ -51,6 +51,7 @@ android {
         // "pm clear" command after each test invocation. This command ensures
         // that the app's state is completely cleared between tests.
         testInstrumentationRunnerArguments clearPackageData: 'true'
+        multiDexEnabled true
     }

     sourceSets {
```
