### ISSUE TITLE
Issue with arrow numbers

### ISSUE THREAD

**Issue by DreierF** [DreierF/MyTargets#79]
It is not possible to enter the numbers of arrows because there is no key/button for comma on the keyboard. Also there is no way to select other arrows than first arrows in the arrows listing when you create new training.

**Comment by fregor77** [comment]
About entering arrow numbers, I did this yesterday when creating a new arrow set. Comma was present on my keyboard at least. Google Keyboard, numeric comes up as default.

**Comment by DreierF** [comment]
Like I said on Google plus: +Gizmo Sk​ This must be a bug **caused by your keyboard**. Because I just tell the system that the user should be able to enter numbers and commas. I'll change the input so that it works like the sight settings in the bow activity. Than you don't need commas anymore ;-)
