### ISSUE TITLE
Add End timestamp

### ISSUE THREAD

**Issue by Tirpitz93** [DreierF/MyTargets#88]
increase accuracy of timestamp for each shot in export or add a timestamp for when each end is scored/submitted.

**Comment by DreierF** [comment]
Can you provide any use case for this?

**Comment by Tirpitz93** [comment]
I Would like to see if and how rests and time between ends affects
shooting, I am planning to use this app extensively and import the data to
pc to analyse. an arrow timestamp would do, as it will normally be
essentially the same for each arrow in an end.

**Comment by DreierF** [comment]
Good idea. Since this is fairly easy to implement, it should not be a problem.
