### ISSUE TITLE
End comments

### ISSUE THREAD

**Issue by Tirpitz93** [DreierF/MyTargets#89]
add ability to add comments to each end

**Comment by DreierF** [comment]
You can already add comments to individual shots. Do you see any advantage in allowing to comment ends and shots?

**Comment by Tirpitz93** [comment]
Well during practice I normally focus on one aspect of the shot for each end, I would like to record this to see which aspects have the largest effect on accuracy. Personally not for each shot as I do not use numbered arrows, and I shoot to large ends to remember where each shot went and what I was doing.

**Comment by DreierF** [comment]
Agreed. PRs are welcomed ;-)

**Comment by Tirpitz93** [comment]
I am currently downloading android studio to my laptop, but I am on summer season so the internet is abysmally slow, I will have a look as soon as I get my dev environment set up.

**Comment by DreierF** [comment]
Closed with 0807312
