### ISSUE TITLE
crash when adding new round to training

### ISSUE THREAD

**Issue by Tirpitz93** [DreierF/MyTargets#91]
* functioned normally for one round (20 ends), then started a second round (3 ends).
* crashed when trying to start a third round.

**Comment by DreierF** [comment]
Did you use one of the 3D target faces? If yes then this has been fixed with af79dbf0337d157810a1f9e09339e4cdb248fe89

**Comment by DreierF** [comment]
@Tirpitz93 Can you still reproduce this? Otherwise lets close this ;-)
